######################################################################
# Automatically generated by qmake (3.0) ? 1? 16 17:12:09 2014
######################################################################

TEMPLATE = app
TARGET = example
CONFIG+=debug c++11
INCLUDEPATH += .
QT += widgets
include(../src/QTwitterIO.pro)
# Input
HEADERS += example.hpp
SOURCES += example.cpp
